//
// Generated file, do not edit! Created by nedtool 5.0 from fat_tree.msg.
//

#ifndef __FAT_TREE_M_H
#define __FAT_TREE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>fat_tree.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * message FatTreeMsg
 * {
 *     //int someField;
 *     //string anotherField;
 *     //double arrayField1[];
 *     //double arrayField2[10];
 *     int src_ppid; //源processor的physical id
 *     int dst_ppid; //目标processor的physical id
 *     int from_router_port; //记录从当前路由器的哪一个端口收到该msg，由上一个路由器计算出
 *     string anotherField;
 *     int hopCount = 0;
 *     int vc_id; //virtual channel id
 * }
 * </pre>
 */
class FatTreeMsg : public ::omnetpp::cMessage
{
  protected:
    int src_ppid;
    int dst_ppid;
    int from_router_port;
    ::omnetpp::opp_string anotherField;
    int hopCount;
    int vc_id;

  private:
    void copy(const FatTreeMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const FatTreeMsg&);

  public:
    FatTreeMsg(const char *name=nullptr, int kind=0);
    FatTreeMsg(const FatTreeMsg& other);
    virtual ~FatTreeMsg();
    FatTreeMsg& operator=(const FatTreeMsg& other);
    virtual FatTreeMsg *dup() const {return new FatTreeMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual int getSrc_ppid() const;
    virtual void setSrc_ppid(int src_ppid);
    virtual int getDst_ppid() const;
    virtual void setDst_ppid(int dst_ppid);
    virtual int getFrom_router_port() const;
    virtual void setFrom_router_port(int from_router_port);
    virtual const char * getAnotherField() const;
    virtual void setAnotherField(const char * anotherField);
    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);
    virtual int getVc_id() const;
    virtual void setVc_id(int vc_id);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const FatTreeMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, FatTreeMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __FAT_TREE_M_H

